language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

git:
  quiet: true
  depth: false

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - php vendor/bin/phpcs

after_script:
  - php vendor/bin/codacycoverage clover ./build/logs/clover.xml
