<?php

/**
 * @file
 * Contains github_cards.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function github_cards_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the github_cards module.
    case 'help.page.github_cards':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('GitHub user and repo cards.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function github_cards_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function github_cards_theme_suggestions_github_card(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#github_card'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'github_card__' . $sanitized_view_mode;
  $suggestions[] = 'github_card__' . $entity->bundle();
  $suggestions[] = 'github_card__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'github_card__' . $entity->id();
  $suggestions[] = 'github_card__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
